### ISSUE TITLE
creating and hosting sitemap.xml

### ISSUE THREAD

**Issue by ksonda** [internetofwater/pids.geoconnex.us#7]
@fils , in a general sense, is this how you would need sitemap.xml made available? (we have roughly 3 million PIDs at the moment)

https://developers.google.com/search/docs/advanced/sitemaps/large-sitemaps

Is it possible to have nested sitemap indexes?

For example, we have many namespaces, /orgA /orgB /orgC, and each of these might have multiple categories of pids /orgX/sites, /orgX/wells, etc. each of which may have more than 50k urls.

Is it ok to have an overal sitemap index.xml that points to namespace-specific sitemap index.xml that themselves refer to category sitemap index.xml that then point to 50k pages of sitemap.xml?

**Comment by ksonda** [comment]
In general there's probably going to be a lot of noncompliant json-ld from contributing orgs.

https://geoconnex.us/cuahsi/his/NHGS_WOF/LOVOTECS-CAR 

contexts with things like : "name": "schema.name" and such

**Comment by fils** [comment]
@ksonda so yeah, that is not so good.   

That page's JSON-LD not even formed correctly.  Gleaner will log an error for it.  

Even when fixed there are other issues as you point out.   This is why I think SHACL may be important sooner than later.  We can combine SHACL shapes with notebooks people can run from mybinder or Google Colab that let them assess their holdings. 

Otherwise you are going to have issues in recovery in SPARQL  or you end of with ugly SPARQL to compensate for these issues that has performance issues.   I've seen both. :)
